### PR TITLE
[to debug] sth is wrong with kibana

### PR DESCRIPTION
**Pull request by coutoPL**
Steps to reproduce:
1. run `./run_elasticsearch_and_kibana.sh`
2. wait for ES and KBN to start
3. open `http://localhost:5601` in the browser
4. log in with credentials `user:test` 
5. you should be logged and then you should see:

Screenshot 2022-02-04 at 19 56 38

### CODE REVIEW

**Comment by Dzuming** [comment]
Fixed, just removed `indices: ["roa-logs-random-*"]` from `ReadonlyREST.yml`
image

**Comment by Dzuming** [comment]
@coutoPL I cannot push a commit to this repo (I generated personal token with required scoped) so looks like you need to change it in the code by your own :( 
image

**Comment by Dzuming** [comment]
It looks like this problem is because `roa-logs-random-*` probably doesn't exist if you change indices into a `indices: [ "*" ]` it should work as expected

**Comment by coutoPL** [comment]
Thanks for the hint. I forgot that I should create block for kibana with kibana_ rules. In task we will discuss how to improve the UX to inform user about misconfiguration. Thx again

**Pull request closed without merging**
