### PR TITLE
[RORDEV-1287] Kibana SSL

### PR DESCRIPTION
**Pull request by coutoPL**
changes:
* kibana SSL
* old kibana version-related fix

### CODE REVIEW

**Comment by coutoPL** [comment]
@Dzuming kindly reminder ;)

**Review by Dzuming — APPROVED** [review]
Oh, sorry, i thought that it must help with an issue reproduction for now. AFAIR I tested it and it works as expected

**Comment by coutoPL** [comment]
Having SSL in our sandbox is a good default so I assumed we want to have it the master branch

**Comment by Dzuming** [comment]
> Having SSL in our sandbox is a good default so I assumed we want to have it the master branch

Yes, of course, I just tried to find an excuse for why didn't I accept it earlier ;)

**Comment by coutoPL** [comment]
Yeah ;) no problem at all ;)

**Pull request merged**
